import type { DatabaseEngine, TableColumnDefinition, TableSchemaMutation } from 'types';
import { databaseEngineFamily, quoteDatabaseIdentifier } from '@/lib/databaseEngines';

function literal(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function tableName(database: string, table: string, engine: DatabaseEngine) {
  return `${quoteDatabaseIdentifier(database, engine)}.${quoteDatabaseIdentifier(table, engine)}`;
}

function columnSql(column: TableColumnDefinition, engine: DatabaseEngine) {
  const quote = (value: string) => quoteDatabaseIdentifier(value, engine);
  const family = databaseEngineFamily(engine);
  const type = `${column.dataType}${column.length ? `(${column.length})` : ''}`;
  const parts = [quote(column.name), type];
  if (family === 'mysql' && column.unsigned) parts.push('UNSIGNED');
  if (family === 'mysql' && column.zerofill) parts.push('ZEROFILL');
  parts.push(column.nullable ? 'NULL' : 'NOT NULL');
  if (column.autoIncrement) parts.push(family === 'mysql' ? 'AUTO_INCREMENT' : family === 'mssql' ? 'IDENTITY(1,1)' : 'GENERATED BY DEFAULT AS IDENTITY');
  if (column.defaultKind === 'null') parts.push('DEFAULT NULL');
  if (column.defaultKind === 'literal') parts.push(`DEFAULT ${literal(column.defaultValue || '')}`);
  if (column.defaultKind === 'expression' && column.defaultValue) parts.push(`DEFAULT ${column.defaultValue}`);
  if (column.generatedExpression) parts.push(`GENERATED ALWAYS AS (${column.generatedExpression})${family === 'mysql' ? ` ${column.generatedStorage || 'VIRTUAL'}` : ''}`);
  if (family === 'mysql' && column.comment) parts.push(`COMMENT ${literal(column.comment)}`);
  return parts.join(' ');
}

export function migrationSqlForMutation(database: string, table: string, mutation: TableSchemaMutation, engine: DatabaseEngine) {
  const target = tableName(database, table, engine);
  const quote = (value: string) => quoteDatabaseIdentifier(value, engine);
  const family = databaseEngineFamily(engine);

  switch (mutation.kind) {
    case 'add-column': {
      const position = family === 'mysql' ? mutation.first ? ' FIRST' : mutation.after ? ` AFTER ${quote(mutation.after)}` : '' : '';
      return `ALTER TABLE ${target} ADD COLUMN ${columnSql(mutation.column, engine)}${position};`;
    }
    case 'modify-column': {
      const position = family === 'mysql' ? mutation.first ? ' FIRST' : mutation.after ? ` AFTER ${quote(mutation.after)}` : '' : '';
      if (family === 'mysql') return `ALTER TABLE ${target} CHANGE COLUMN ${quote(mutation.originalName)} ${columnSql(mutation.column, engine)}${position};`;
      return `-- ${family} motorunda kolon adı/tip değişikliği ayrı ifadeler gerektirebilir.\nALTER TABLE ${target} ALTER COLUMN ${quote(mutation.originalName)} TYPE ${mutation.column.dataType}${mutation.column.length ? `(${mutation.column.length})` : ''};`;
    }
    case 'drop-column':
      return `ALTER TABLE ${target} DROP COLUMN ${quote(mutation.columnName)};`;
    case 'add-index': {
      const columns = mutation.index.columns.map(column => `${quote(column.name)}${column.order ? ` ${column.order}` : ''}`).join(', ');
      if (mutation.index.kind === 'PRIMARY') return `ALTER TABLE ${target} ADD PRIMARY KEY (${columns});`;
      const unique = mutation.index.kind === 'UNIQUE' ? 'UNIQUE ' : '';
      const name = mutation.index.name || `idx_${table}_${mutation.index.columns.map(column => column.name).join('_')}`;
      return `CREATE ${unique}INDEX ${quote(name)} ON ${target} (${columns});`;
    }
    case 'drop-index':
      return family === 'mysql' ? `ALTER TABLE ${target} DROP INDEX ${quote(mutation.indexName)};` : `DROP INDEX ${quote(mutation.indexName)};`;
    case 'add-foreign-key': {
      const fk = mutation.foreignKey;
      const local = fk.columns.map(quote).join(', ');
      const referenced = `${quote(fk.referencedDatabase || database)}.${quote(fk.referencedTable)}`;
      const remote = fk.referencedColumns.map(quote).join(', ');
      return `ALTER TABLE ${target} ADD CONSTRAINT ${quote(fk.name)} FOREIGN KEY (${local}) REFERENCES ${referenced} (${remote}) ON DELETE ${fk.onDelete || 'RESTRICT'} ON UPDATE ${fk.onUpdate || 'RESTRICT'};`;
    }
    case 'drop-foreign-key':
      return family === 'mysql' ? `ALTER TABLE ${target} DROP FOREIGN KEY ${quote(mutation.constraintName)};` : `ALTER TABLE ${target} DROP CONSTRAINT ${quote(mutation.constraintName)};`;
    case 'table-options': {
      const statements: string[] = [];
      if (mutation.name && mutation.name !== table) statements.push(family === 'mysql' ? `RENAME TABLE ${target} TO ${tableName(database, mutation.name, engine)};` : `ALTER TABLE ${target} RENAME TO ${quote(mutation.name)};`);
      if (family === 'mysql') {
        const clauses = [
          mutation.engine ? `ENGINE=${mutation.engine}` : '',
          mutation.collation ? `COLLATE=${mutation.collation}` : '',
          mutation.autoIncrement ? `AUTO_INCREMENT=${mutation.autoIncrement}` : '',
          mutation.rowFormat ? `ROW_FORMAT=${mutation.rowFormat}` : '',
          mutation.comment !== undefined ? `COMMENT=${literal(mutation.comment)}` : ''
        ].filter(Boolean);
        if (clauses.length) statements.push(`ALTER TABLE ${target} ${clauses.join(' ')};`);
      }
      return statements.join('\n') || `-- ${target} için değiştirilecek tablo seçeneği bulunamadı.`;
    }
  }
}

export function migrationDownSql(snapshotCreateSql: string, database: string, table: string, engine: DatabaseEngine) {
  const target = tableName(database, table, engine);
  return `-- DİKKAT: Bu geri alma planı tabloyu snapshot yapısıyla yeniden oluşturur.\n-- Veriyi korumak için uygulamadan önce ayrıca veri yedeği alın.\nDROP TABLE IF EXISTS ${target};\n${snapshotCreateSql.replace(/;?\s*$/, ';')}`;
}

export function migrationFileName(database: string, table: string) {
  const date = new Date().toISOString().replace(/[-:TZ.]/g, '').slice(0, 14);
  const safe = `${database}_${table}`.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();
  return `${date}_${safe}.sql`;
}

export function looksLikeProductionServer(name: string, host?: string) {
  return /(^|[\s._-])(prod|production|live|canli|canlı)([\s._-]|$)/i.test(`${name} ${host || ''}`);
}
